In [ ]:
import pandas as pd

# Load the dataset
data_path = '/content/sample_data/train.csv'
used_cars_data = pd.read_csv(data_path)
used_cars_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

In [ ]:
# Droping the 'New_Price' column
used_cars_data.drop('New_Price', axis=1, inplace=True)

# missing values for 'Seats' with mode
seats_mode = used_cars_data['Seats'].mode()[0]
used_cars_data['Seats'].fillna(seats_mode, inplace=True)

In [ ]:
# Ensuring that 'Mileage' is correctly converted to numeric across the entire column
used_cars_data['Mileage'] = used_cars_data['Mileage'].str.extract('(\d+.\d+)').astype(float)

# Recalculating median for 'Mileage' after ensuring all data is numeric
mileage_median = used_cars_data['Mileage'].median()

# Proceeding with imputations for 'Mileage' after conversion
used_cars_data['Mileage'].fillna(mileage_median, inplace=True)

# Final verification for any missing values
used_cars_data.isnull().sum()

Unnamed: 0            0
Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine               36
Power                36
Seats                 0
Price                 0
dtype: int64

In [ ]:
used_cars_data['Engine'] = used_cars_data['Engine'].str.extract('(\d+.\d+)').astype(float)
engine_median = used_cars_data['Engine'].median()
used_cars_data['Engine'].fillna(engine_median, inplace=True)
used_cars_data.isnull().sum()

Unnamed: 0            0
Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine                0
Power                36
Seats                 0
Price                 0
dtype: int64

In [ ]:
used_cars_data['Power'] = used_cars_data['Power'].str.extract('(\d+.\d+)').astype(float)
power_median = used_cars_data['Power'].median()
used_cars_data['Power'].fillna(power_median, inplace=True)
used_cars_data.isnull().sum()

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

In [ ]:
# One-hot encoding categorical variables 'Fuel_Type' and 'Transmission'
encoded_data = pd.get_dummies(used_cars_data, columns=['Fuel_Type', 'Transmission'], drop_first=True)

encoded_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,12.50,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,18.19,1199.0,88.70,5.0,4.50,0,1,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,6.00,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,17.74,0,0,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,3.50,0,0,1

In [ ]:
# Since we're working in Python, we'll perform the equivalent operation of R's mutate function to create a new feature.
# We will calculate the current age of the car by subtracting the "Year" value from the current year (2024).

encoded_data['Car_Age'] = 2024 - encoded_data['Year']

encoded_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,12.50,0,0,1,9
1,2,Honda Jazz V,Chennai,2011,46000,First,18.19,1199.0,88.70,5.0,4.50,0,1,1,13
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,6.00,0,0,1,12
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,17.74,0,0,0,11
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,3.50,0,0,1,11

`Seclect`

In [ ]:
# Select operation
selected_data = encoded_data[['Location', 'Year', 'Fuel_Type_Petrol', 'Transmission_Manual', 'Car_Age']]

selected_data.head()

     Location  Year  Fuel_Type_Petrol  Transmission_Manual  Car_Age
0        Pune  2015                 0                    1        9
1     Chennai  2011                 1                    1       13
2     Chennai  2012                 0                    1       12
3  Coimbatore  2013                 0                    0       11
4      Jaipur  2013                 0                    1       11

`filter`

In [ ]:
# Filter operation
filtered_data = encoded_data[(encoded_data['Transmission_Manual'] == 1) & (encoded_data['Fuel_Type_Petrol'] == 1)]
filtered_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
1,2,Honda Jazz V,Chennai,2011,46000,First,18.19,1199.0,88.70,5.0,4.50,0,1,1,13
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,First,21.56,1462.0,103.25,5.0,9.95,0,1,1,6
21,23,Hyundai i20 1.2 Magna,Kolkata,2010,45807,First,18.50,1197.0,103.60,5.0,1.87,0,1,1,14
23,25,Honda City Corporate Edition,Mumbai,2012,51920,First,16.80,1497.0,116.30,5.0,4.25,0,1,1,12
25,27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Second,20.92,998.0,67.10,5.0,2.75,0,1,1,11

`rename` and `mutate`

In [ ]:
# Rename operation
renamed_data = encoded_data.rename(columns={'Kilometers_Driven': 'Kms_Driven'})
# Mutate operation: a column indicating if the car is over 5 years old
renamed_data['Age_Over_5'] = renamed_data['Car_Age'] > 5
renamed_data[['Location', 'Kms_Driven', 'Age_Over_5']].head()

     Location  Kms_Driven  Age_Over_5
0        Pune       41000        True
1     Chennai       46000        True
2     Chennai       87000        True
3  Coimbatore       40670        True
4      Jaipur       86999        True

`arrange`

In [ ]:
# Arrange operation: Sorting the cars by Price in descending order
arranged_data = renamed_data.sort_values(by='Price', ascending=False)
arranged_data[['Location', 'Price']].head()

        Location   Price
3952   Hyderabad  160.00
5620       Delhi  120.00
5752   Hyderabad  100.00
1457       Kochi   97.07
1917  Coimbatore   93.67

`Group By`

In [ ]:
# Summarizing with Group By operation: Grouping by Location and calculating the average Price and average Car_Age
grouped_summary = renamed_data.groupby('Location').agg(Avg_Price=('Price', 'mean'), Avg_Car_Age=('Car_Age', 'mean')).reset_index()
grouped_summary.head()

     Location  Avg_Price  Avg_Car_Age
0   Ahmedabad   8.567248    10.660550
1   Bangalore  13.482670    11.161932
2     Chennai   7.958340    11.926471
3  Coimbatore  15.160206     8.583201
4       Delhi   9.881944    10.653704